### ISSUE TITLE
What is the hotkey to toggle modes

### ISSUE THREAD

**Issue by dustingetz** [shaunlebron/parinfer-codemirror#12]

**Comment by shaunlebron** [comment]
never actually thought to setup a hotkey by default.  you have to bind it yourself to the function to switch modes

**Comment by dustingetz** [comment]
For the next guy, here is how I did it:

```
(if (and (:parinfer props) (= "clojure" (:mode props)))
  (do
    (js/parinferCodeMirror.init ref)
    ; `mode` is 'paren', 'indent', or 'smart'
    (.addKeyMap ref #js {"Ctrl-1" #(let [mode (goog.object/getValueByKeys ref "__parinfer__" "mode")
                                         mode (case mode "paren" "indent" "paren")]
                                     (js/parinferCodeMirror.setMode ref mode))})))
```

**Comment by dustingetz** [comment]
The problem is that you need a visual indicator to indicate what mode you're in (in addition to the hotkey). I was able to abuse the locus functionality to accomplish this - it shows the locus when in indent mode. Here is the final result - Watch for the locus toggling, it is subtle! This is really cool!

I am not sure what will come of this, but for the next guy, my hacks are here: https://github.com/hyperfiddle/hyperfiddle/blob/e50b7407be464995eb3bf62c843e230911cb13e6/src/contrib/ui/codemirror.cljs#L44-L49

![xpdc4wy](https://user-images.githubusercontent.com/124158/43361589-664198a2-92a0-11e8-9bf5-9283c3915dfe.gif)

**Comment by dustingetz** [comment]
@shaunlebron Can I contact you by email?

**Comment by shaunlebron** [comment]
yes

**Comment by dustingetz** [comment]
@shaunlebron what is your email
