### ISSUE TITLE
What is :locus true?

### ISSUE THREAD

**Issue by dustingetz** [shaunlebron/parinfer-codemirror#14]

**Comment by dustingetz** [comment]
I think it means to hide the closing parens:
![image](https://user-images.githubusercontent.com/124158/43361086-3f220452-9294-11e8-92a5-c3cb59f981c4.png)

**Comment by shaunlebron** [comment]
locus was an experiment—replacing close-parens at the end of multi-line
expressions with indent guides.

(showed it to several people and the feedback was unanimously negative)

**Comment by dustingetz** [comment]
Ah! I see now – the indent guidelines – thanks.

![image](https://user-images.githubusercontent.com/124158/43361124-1f082484-9295-11e8-9bfe-0ebee09b8f8f.png)
