### ISSUE TITLE
dark mode / light mode

### ISSUE THREAD

**Issue by raymcdermott** [shaunlebron/parinfer-codemirror#16]
Hi @shaunlebron - I am using this project with replete/replete-web and loving it so far.

One aspect that I would like to add is the ability to be in synch with the OS dark / light mode setting. It seems like we can discover the mode on [Windows](https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode) and [MacOS](https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers) using client side JS.

Having that info, do you have any thoughts on the best way to express these different modes with `parinfer-codemirror`? 

For example, would it be interesting to have dark/light CSS files and extend the API to toggle between the two?

**Comment by shaunlebron** [comment]
In general, I’d just point you to styling docs for CodeMirror since this isn’t Parinfer specific:
https://codemirror.net/doc/manual.html#styling

**Comment by raymcdermott** [comment]
ok thanks. I'll close it.
